In [41]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [42]:
df=pd.read_csv('FuelConsumptionCo2.csv')
df.sample(5)

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
809,2014,MINI,JOHN COOPER WORKS COUNTRYMAN ALL4,COMPACT,1.6,4,M6,Z,9.3,7.5,8.5,33,196
398,2014,FORD,FLEX AWD,SUV - STANDARD,3.5,6,AS6,X,13.7,10.2,12.1,23,278
511,2014,HYUNDAI,SANTA FE SPORT 4WD,SUV - SMALL,2.0,4,A6,X,12.9,9.7,11.5,25,264
813,2014,MINI,JOHN COOPER WORKS PACEMAN ALL4,COMPACT,1.6,4,M6,Z,9.3,7.5,8.5,33,196
844,2014,NISSAN,GT-R,SUBCOMPACT,3.8,6,AM6,Z,14.5,10.9,12.9,22,297

In [43]:
df.describe()

,MODELYEAR,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
count,1067.0,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000
mean,2014.0,3.346298,5.794752,13.296532,9.474602,11.580881,26.441425,256.228679
std,0.0,1.415895,1.797447,4.101253,2.794510,3.485595,7.468702,63.372304
min,2014.0,1.000000,3.000000,4.600000,4.900000,4.700000,11.000000,108.000000
25%,2014.0,2.000000,4.000000,10.250000,7.500000,9.000000,21.000000,207.000000
50%,2014.0,3.400000,6.000000,12.600000,8.800000,10.900000,26.000000,251.000000
75%,2014.0,4.300000,8.000000,15.550000,10.850000,13.350000,31.000000,294.000000
max,2014.0,8.400000,12.000000,30.200000,20.500000,25.800000,60.000000,488.000000

In [44]:
# Drop categoricals and any unseless columns
df = df.drop(['MODELYEAR', 'MAKE', 'MODEL', 'VEHICLECLASS', 'TRANSMISSION', 'FUELTYPE',],axis=1)

In [45]:
df.corr()

,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
ENGINESIZE,1.000000,0.934011,0.832225,0.778746,0.819482,-0.808554,0.874154
CYLINDERS,0.934011,1.000000,0.796473,0.724594,0.776788,-0.770430,0.849685
FUELCONSUMPTION_CITY,0.832225,0.796473,1.000000,0.965718,0.995542,-0.935613,0.898039
FUELCONSUMPTION_HWY,0.778746,0.724594,0.965718,1.000000,0.985804,-0.893809,0.861748
FUELCONSUMPTION_COMB,0.819482,0.776788,0.995542,0.985804,1.000000,-0.927965,0.892129
FUELCONSUMPTION_COMB_MPG,-0.808554,-0.770430,-0.935613,-0.893809,-0.927965,1.000000,-0.906394
CO2EMISSIONS,0.874154,0.849685,0.898039,0.861748,0.892129,-0.906394,1.000000

In [46]:
df = df.drop(['CYLINDERS', 'FUELCONSUMPTION_CITY', 'FUELCONSUMPTION_HWY','FUELCONSUMPTION_COMB',],axis=1)

In [47]:
df.head(9)

   ENGINESIZE  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS
0         2.0                        33           196
1         2.4                        29           221
2         1.5                        48           136
3         3.5                        25           255
4         3.5                        27           244
5         3.5                        28           230
6         3.5                        28           232
7         3.7                        25           255
8         3.7                        24           267

In [48]:
X = df[['ENGINESIZE','FUELCONSUMPTION_COMB_MPG']]
y = df['CO2EMISSIONS']

In [49]:
from sklearn import preprocessing

std_scaler = preprocessing.StandardScaler()
X_std = std_scaler.fit_transform(X)

In [50]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_std,y,test_size=0.2,random_state=42)

In [51]:
from sklearn import linear_model

regressor = linear_model.LinearRegression()
regressor.fit(X_train, y_train)

coef_ =  regressor.coef_
intercept_ = regressor.intercept_

print ('Coefficients: ',coef_)
print ('Intercept: ',intercept_)

Coefficients:  [ 25.27339614 -37.4381472 ]
Intercept:  256.2907248808642

In [52]:
means_ = std_scaler.mean_
std_devs_ = std_scaler.scale_

coef_original = coef_ / std_devs_
intercept_original = intercept_ - np.sum((means_ * coef_) / std_devs_)

print ('Coefficients: ', coef_original)
print ('Intercept: ', intercept_original)

Coefficients:  [17.8581369  -5.01502179]
Intercept:  329.1363967025387

In [53]:
from sklearn.metrics import mean_squared_error

In [54]:
y_pred = regressor.predict(X_test)
mean_squared_error(y_test,y_pred)

466.1131199661165